import { Edge } from '@xyflow/react';
import { RobotNode } from '../store/useRobotStore';

// Sanitize a human-typed label into a valid Java identifier
const toJavaIdentifier = (str: string): string => {
  let clean = str.replace(/[^a-zA-Z0-9_]/g, '');
  if (!/^[a-zA-Z_]/.test(clean)) clean = '_' + clean;
  return clean || 'hardware_device';
};

// ─────────────────────────────────────────────────────────────────────────────
// Java Code Generator
// ─────────────────────────────────────────────────────────────────────────────
export function generateJavaCode(nodes: RobotNode[], edges: Edge[]): string {
  if (nodes.length === 0) {
    return [
      '// No hardware components have been added to the workspace yet.',
      '// Add components from the sidebar to generate a RobotHardware class.',
    ].join('\n');
  }

  const imports = new Set<string>([
    'import com.qualcomm.robotcore.hardware.HardwareMap;',
    'import com.qualcomm.robotcore.util.ElapsedTime;',
  ]);

  let declarations = '';
  let initializations = '';

  // Build edge map: source node id → connected handle on the target (hub) node
  const edgeMap = new Map<string, { targetHandle: string; sourceNodeId: string }>();
  edges.forEach((edge) => {
    if (edge.target && edge.targetHandle) {
      edgeMap.set(edge.source, { targetHandle: edge.targetHandle, sourceNodeId: edge.target });
    }
  });

  nodes.forEach((node) => {
    const varName = toJavaIdentifier(node.data.label);
    const hwType = node.data.hardwareType;

    if (node.type === 'ControlHub') {
      imports.add('import com.qualcomm.robotcore.hardware.DcMotorEx;');
      imports.add('import com.qualcomm.robotcore.hardware.Servo;');
      declarations += `    // ── REV Control Hub: ${varName} ──\n`;
      declarations += `    public DcMotorEx motor_0, motor_1, motor_2, motor_3;\n`;
      declarations += `    public Servo servo_0, servo_1, servo_2, servo_3;\n\n`;
      initializations += `        // Control Hub motor ports\n`;
      initializations += `        motor_0 = hwMap.get(DcMotorEx.class, "motor_0");\n`;
      initializations += `        motor_1 = hwMap.get(DcMotorEx.class, "motor_1");\n`;
      initializations += `        motor_2 = hwMap.get(DcMotorEx.class, "motor_2");\n`;
      initializations += `        motor_3 = hwMap.get(DcMotorEx.class, "motor_3");\n`;
      initializations += `        // Control Hub servo ports\n`;
      initializations += `        servo_0 = hwMap.get(Servo.class, "servo_0");\n`;
      initializations += `        servo_1 = hwMap.get(Servo.class, "servo_1");\n\n`;
    } else if (hwType === 'DcMotor') {
      imports.add('import com.qualcomm.robotcore.hardware.DcMotorEx;');
      declarations += `    public DcMotorEx ${varName};\n`;
      initializations += `        ${varName} = hwMap.get(DcMotorEx.class, "${varName}");\n`;
    } else if (hwType === 'Servo') {
      imports.add('import com.qualcomm.robotcore.hardware.Servo;');
      declarations += `    public Servo ${varName};\n`;
      initializations += `        ${varName} = hwMap.get(Servo.class, "${varName}");\n`;
    } else if (hwType === 'ColorSensor') {
      imports.add('import com.qualcomm.robotcore.hardware.NormalizedColorSensor;');
      const conn = edgeMap.get(node.id);
      const physicalName = conn ? conn.targetHandle : varName;
      declarations += `    public NormalizedColorSensor ${varName};\n`;
      initializations += `        ${varName} = hwMap.get(NormalizedColorSensor.class, "${physicalName}");\n`;
    } else if (hwType === 'Webcam') {
      imports.add('import org.firstinspires.ftc.robotcore.external.hardware.camera.WebcamName;');
      declarations += `    public WebcamName ${varName};\n`;
      initializations += `        ${varName} = hwMap.get(WebcamName.class, "${varName}");\n`;
    } else if (hwType === 'Sensor') {
      imports.add('import com.qualcomm.robotcore.hardware.NormalizedColorSensor;');
      const conn = edgeMap.get(node.id);
      const physicalName = conn ? conn.targetHandle : 'i2c_0';
      declarations += `    public NormalizedColorSensor ${varName};\n`;
      initializations += `        ${varName} = hwMap.get(NormalizedColorSensor.class, "${physicalName}");\n`;
    } else if (hwType === 'Coprocessor') {
      declarations += `    // Linux Coprocessor: ${varName} (communicates over USB Serial)\n`;
      initializations += `        // TODO: initialize serial/USB link for ${varName}\n`;
    }
  });

  const sortedImports = Array.from(imports).sort().join('\n');
  const stamp = new Date().toLocaleString();

  return `package org.firstinspires.ftc.teamcode;

${sortedImports}

/**
 * Auto-Generated by SysMod Studio  ·  MBSE Engine
 * Build Stamp : ${stamp}
 *
 * DO NOT MODIFY — regenerate from SysMod Studio to update.
 */
public class RobotHardware {

    /* ── Hardware Members (mapped from workspace topology) ── */
${declarations}
    /* ── Internal State ── */
    HardwareMap hwMap  = null;
    private ElapsedTime period = new ElapsedTime();

    public RobotHardware() {}

    /**
     * Initialize every hardware member from the active OpMode HardwareMap.
     *
     * @param ahwMap  the HardwareMap supplied by the OpMode
     */
    public void init(HardwareMap ahwMap) {
        hwMap = ahwMap;

${initializations}    }
}
`;
}
// ─────────────────────────────────────────────────────────────────────────────
// AADL Code Generator
// ─────────────────────────────────────────────────────────────────────────────
const DEVICE_FEATURES: Record<string, string> = {
  ControlHub:
    '    motor_port_0 : out data port;\n' +
    '    motor_port_1 : out data port;\n' +
    '    motor_port_2 : out data port;\n' +
    '    motor_port_3 : out data port;\n' +
    '    servo_port_0 : out data port;\n' +
    '    servo_port_1 : out data port;\n' +
    '    i2c_bus_0    : out data port;\n' +
    '    usb_host     : out data port;\n' +
    '    -- Integrated Sensors\n' +
    '    imu_out      : out data port;\n' +
    '    voltage_out  : out data port;\n' +
    '    current_out  : out data port;',
  DcMotor:    '    power_in      : in  data port;',
  Servo:      '    pwm_in        : in  data port;',
  ColorSensor:'    i2c_out       : out data port;',
  Webcam:     '    usb_link      : in  data port;',
  Sensor:     '    i2c_out       : out data port;',
  Coprocessor:'    usb_serial    : in out data port;',
};

function buildDeviceBlock(hwType: string): string {
  const features = DEVICE_FEATURES[hwType] ?? '    data : in out data port;';
  return (
    `  device ${hwType}\n  features\n${features}\n  end ${hwType};\n\n` +
    `  device implementation ${hwType}.impl\n  end ${hwType}.impl;\n`
  );
}

export function generateAadlCode(nodes: RobotNode[], edges: Edge[]): string {
  const stamp = new Date().toLocaleString();

  if (nodes.length === 0) {
    return `-- ============================================================
-- AADL System Architecture Model
-- Auto-Generated by SysMod Studio  ·  MBSE Engine
-- Build: ${stamp}
-- ============================================================

-- No hardware components have been added yet.
-- Add components from the sidebar to populate the architecture.

package RobotSystem
public
  with SEI;

  system Robot
  end Robot;

  system implementation Robot.impl
    subcomponents
      -- (empty)
  end Robot.impl;

end RobotSystem;
`;
  }

  let subcomponents = '';
  let connections = '';
  const seenTypes = new Set<string>();
  let deviceBlocks = '';
  let ci = 1;

  nodes.forEach((node) => {
    const varName = toJavaIdentifier(node.data.label);
    const hwType = node.type === 'ControlHub' ? 'ControlHub' : node.data.hardwareType;
    subcomponents += `      ${varName.padEnd(22)}: device ${hwType}.impl;\n`;
    if (!seenTypes.has(hwType)) {
      seenTypes.add(hwType);
      deviceBlocks += buildDeviceBlock(hwType) + '\n';
    }
  });

  edges.forEach((edge) => {
    const src = nodes.find((n) => n.id === edge.source);
    const tgt = nodes.find((n) => n.id === edge.target);
    if (src && tgt) {
      const srcVar = toJavaIdentifier(src.data.label);
      const tgtVar = toJavaIdentifier(tgt.data.label);
      const srcHandle = (edge.sourceHandle ?? 'output').replace(/-/g, '_');
      const tgtHandle = (edge.targetHandle ?? 'input').replace(/-/g, '_');
      connections += `      C${String(ci++).padStart(2, '0')} : port ${srcVar}.${srcHandle} -> ${tgtVar}.${tgtHandle};\n`;
    }
  });

  const connectionsSection = connections
    ? `    connections\n${connections}`
    : '    -- connections: define edges between components on the canvas';

  return `-- ============================================================
-- AADL System Architecture Model
-- Auto-Generated by SysMod Studio  ·  MBSE Engine
-- Build: ${stamp}
-- Conforms to AADL v2.3  (AS5506C)
-- ============================================================

package RobotSystem
public
  with SEI;

  -- ──────────────────────────────────────────────────────────
  -- Top-level Robot System
  -- ──────────────────────────────────────────────────────────
  system Robot
  end Robot;

  system implementation Robot.impl
    subcomponents
${subcomponents}
${connectionsSection}
  end Robot.impl;

  -- ──────────────────────────────────────────────────────────
  -- Component Type & Implementation Declarations
  -- ──────────────────────────────────────────────────────────
${deviceBlocks}
end RobotSystem;
`;
}