import React, { useMemo } from 'react';
import { ReactFlow, Background, Controls, NodeTypes } from '@xyflow/react';
import { useRobotStore, HardwareType } from './store/useRobotStore';
import { ControlHubNode } from './components/ControlHubNode';
import { SensorNode } from './components/SensorNode';
import { CoprocessorNode } from './components/CoprocessorNode';
import { Cpu, Plus, FileCode, Layers, Trash2 } from 'lucide-react';
import '@xyflow/react/dist/style.css';

export default function App(): React.JSX.Element {
  const { nodes, edges, onNodesChange, onEdgesChange, onConnect, addDevice, clearWorkspace } = useRobotStore();

  const nodeTypes = useMemo<NodeTypes>(() => ({
    ControlHub: ControlHubNode,
    Sensor: SensorNode,
    Coprocessor: CoprocessorNode
  }), []);

  // Structural Code Generator mapping active visual canvas nodes directly to standard FTC Java SDK code boilerplate
  const handleExportHardwareCode = async (): Promise<void> => {
    // Helper to sanitize human-typed labels into legal, safe Java variable names
  const toJavaIdentifier = (str: string): string => {
    let clean = str.replace(/[^a-zA-Z0-9_]/g, '');
    if (!/^[a-zA-Z_]/.test(clean)) {
      clean = '_' + clean;
    }
    return clean || 'hardware_device';
  };

  const handleExportHardwareCode = async (): Promise<void> => {
    let internalDeclarations = '';
    let initializations = '';

    // Track assigned connection ports from your active layout configuration edges
    const edgeMap = new Map<string, { targetHandle: string; sourceNodeId: string }>();
    edges.forEach((edge) => {
      if (edge.target && edge.targetHandle) {
        edgeMap.set(edge.source, { targetHandle: edge.targetHandle, sourceNodeId: edge.target });
      }
    });

    nodes.forEach((node) => {
      const variableName = toJavaIdentifier(node.data.label);

      if (node.type === 'ControlHub') {
        internalDeclarations += `    // Master Controller Initialization\n    public DcMotorEx motor_0;\n    public DcMotorEx motor_1;\n`;
        initializations += `        motor_0 = hwMap.get(DcMotorEx.class, "motor_0");\n        motor_1 = hwMap.get(DcMotorEx.class, "motor_1");\n`;
      } 
      else if (node.type === 'Sensor') {
        // Resolve connection edge to find exactly which bus configuration it is wired into
        const connection = edgeMap.get(node.id);
        const physicalHardwareName = connection ? connection.targetHandle : 'i2c_0';
        
        internalDeclarations += `    public NormalizedColorSensor ${variableName};\n`;
        initializations += `        ${variableName} = hwMap.get(NormalizedColorSensor.class, "${physicalHardwareName}");\n`;
      }
    });

    const generatedCode = `package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.NormalizedColorSensor;
import com.qualcomm.robotcore.util.ElapsedTime;

/**
 * Auto-Generated by SysMod Studio (MBSE Engine)
 * Runtime Build Stamp: ${new Date().toLocaleString()}
 */
public class RobotHardware {
    /* Hardware Members labeled from workspace topology */
${internalDeclarations}
    /* Local Hardware Map reference */
    HardwareMap hwMap = null;
    private ElapsedTime period = new ElapsedTime();

    public RobotHardware() {}

    public void init(HardwareMap ahwMap) {
        hwMap = ahwMap;
${initializations}
    }
}`;

    try {
      const response = await window.sysmodAPI.saveJavaFile(generatedCode);
      if (response.success && response.filePath) {
        alert(`Configuration saved successfully to:\n${response.filePath}`);
      }
    } catch (error) {
      console.error('IPC IO failure:', error);
      alert('Critical Error: Failed to write file payload over native runtime bridge.');
    }
  };
  };

  return (
    <div className="flex w-screen h-screen bg-slate-950 text-slate-100 overflow-hidden">
      {/* Sidebar Interface Components */}
      <aside className="w-80 border-r border-slate-800 bg-slate-900 flex flex-col justify-between z-10 shadow-2xl">
        <div className="p-4 space-y-6">
          <div className="flex items-center gap-2 pb-4 border-b border-slate-800">
            <Layers className="text-amber-500 w-6 h-6" />
            <div>
              <h1 className="text-lg font-mono font-black tracking-tight text-slate-100">SysMod Studio</h1>
              <p className="text-[10px] text-slate-400 font-sans tracking-widest uppercase">FTC Subsystem Modeler</p>
            </div>
          </div>

          <div className="space-y-3">
            <h2 className="text-xs font-mono uppercase tracking-wider text-slate-400 px-1">Hardware Blueprinting Components</h2>
            <div className="space-y-2">
              <button 
                onClick={() => addDevice('ControlHub')}
                className="w-full flex items-center justify-between p-2.5 rounded bg-slate-950 hover:bg-slate-800 border border-amber-500/30 text-left transition duration-150 group"
              >
                <div className="flex items-center gap-2">
                  <Cpu className="w-4 h-4 text-amber-500" />
                  <span className="text-xs font-mono text-slate-300">REV Control Hub</span>
                </div>
                <Plus className="w-3.5 h-3.5 text-slate-500 group-hover:text-amber-500 transition" />
              </button>

              <button 
                onClick={() => addDevice('Sensor')}
                className="w-full flex items-center justify-between p-2.5 rounded bg-slate-950 hover:bg-slate-800 border border-cyan-500/30 text-left transition duration-150 group"
              >
                <div className="flex items-center gap-2">
                  <Cpu className="w-4 h-4 text-cyan-400" />
                  <span className="text-xs font-mono text-slate-300">I2C Color Sensor</span>
                </div>
                <Plus className="w-3.5 h-3.5 text-slate-500 group-hover:text-cyan-400 transition" />
              </button>

              <button 
                onClick={() => addDevice('Coprocessor')}
                className="w-full flex items-center justify-between p-2.5 rounded bg-slate-950 hover:bg-slate-800 border border-indigo-500/30 text-left transition duration-150 group"
              >
                <div className="flex items-center gap-2">
                  <Cpu className="w-4 h-4 text-indigo-400" />
                  <span className="text-xs font-mono text-slate-300">Linux Coprocessor</span>
                </div>
                <Plus className="w-3.5 h-3.5 text-slate-500 group-hover:text-indigo-400 transition" />
              </button>
            </div>
          </div>
        </div>

        <div className="p-4 border-t border-slate-800 space-y-2 bg-slate-950/40">
          <button 
            onClick={clearWorkspace}
            className="w-full py-2 px-3 rounded flex items-center justify-center gap-2 text-xs font-mono bg-slate-900 border border-red-500/20 hover:border-red-500/50 text-red-400 transition"
          >
            <Trash2 className="w-3.5 h-3.5" />
            Clear Canvas
          </button>

          <button 
            onClick={handleExportHardwareCode}
            disabled={nodes.length === 0}
            className="w-full py-3 px-4 rounded flex items-center justify-center gap-2 text-sm font-mono bg-amber-500 text-slate-950 font-bold hover:bg-amber-400 disabled:bg-slate-800 disabled:text-slate-600 disabled:border-transparent transition shadow-lg shadow-amber-500/10"
          >
            <FileCode className="w-4 h-4" />
            Export Code to OS
          </button>
        </div>
      </aside>

      {/* Main Canvas Workspace Viewport */}
      <main className="flex-1 h-full relative bg-slate-950">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          nodeTypes={nodeTypes}
          fitView
        >
          <Background color="#334155" gap={16} size={1} />
          <Controls className="!bg-slate-900 !border-slate-700 !fill-slate-200 [&_button]:!border-slate-800 [&_button]:bg-slate-900" />
        </ReactFlow>
      </main>
    </div>
  );
}